import Workspace from '@/components/workspace/Workspace';
import WorkspaceLabel from '@/components/workspace_label/WorkspaceLabel';
import styles from '@/styles/Home.module.css';
import Head from 'next/head';
import TopBar from '../components/TopBar';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <TopBar />
        <WorkspaceLabel />
        <Workspace />
      </main>
    </>
  )
}
